services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    env_file:
      - ./apps/api-gateway/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    command: pnpm run start:dev api-gateway

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    env_file:
      - ./apps/auth/.env
    volumes:
      - .:/usr/src/app
    command: pnpm run start:dev auth
    depends_on:
      - mysql

  task:
    container_name: task
    build:
      context: .
      dockerfile: ./apps/task/Dockerfile
      target: development
    env_file:
      - ./apps/task/.env
    volumes:
      - .:/usr/src/app
    command: pnpm run start:dev task
    depends_on:
      - mongo

  mysql:
    image: mysql:8.3
    container_name: mysql
    env_file:
      - .env
    ports:
      - '3306:3306'

  mongo:
    image: mongo

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - '5672:5672'
      - '15672:15672'
